(set-register ?e `(file . ,(expand-file-name "emacs.org" user-emacs-directory)))

(defun my/register-save-f1 () (interactive) (point-to-register 'my/register-f1))
(defun my/register-jump-f1 () (interactive) (jump-to-register 'my/register-f1))
(defun my/register-save-f2 () (interactive) (point-to-register 'my/register-f2))
(defun my/register-jump-f2 () (interactive) (jump-to-register 'my/register-f2))
(defun my/register-save-f3 () (interactive) (point-to-register 'my/register-f3))
(defun my/register-jump-f3 () (interactive) (jump-to-register 'my/register-f3))
(defun my/register-save-f4 () (interactive) (point-to-register 'my/register-f4))
(defun my/register-jump-f4 () (interactive) (jump-to-register 'my/register-f4))
