(require 'jabber)
(jabber-connect "tellarite" "gmail.com" "Emacs" nil gmail-pass)
(setq jabber-alert-info-message-hooks (quote (jabber-info-display)))
(setq jabber-alert-presence-hooks nil)
(setq jabber-auto-reconnect t)
(setq jabber-backlog-number 100)
(setq jabber-chatstates-confirm nil)
(setq jabber-global-history-filename "~/.emacs.private/jabber_global_message_log")
(setq jabber-history-dir "~/.emacs.private/jabber-history")
(setq jabber-history-enabled t)
(setq jabber-use-global-history nil)
